homework2

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -28,6 +28,28 @@ jobs:
       with:
         path: ${{github.workspace}}/*.deb
         if-no-files-found: error
+  
+  test:
+    runs-on: ubuntu-20.04
+    needs: build
+    steps:
+    - uses: actions/checkout@v2
+    - name: Install tools
+      run: sudo apt install cmake
+
+    - name: Configure CMake
+      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+
+    - name: Build
+      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+    
+    - run: |
+        if [ "24e7a7b2270daee89c64d3ca5fb3da1a  -" = "$(cat ip_filter.tsv | /home/salavat/project/otus-cpp/build/src/ip_filter | md5sum)" ]; then
+        echo "ok"
+        else
+        echo "failed"
+        exit 1
+        fi
 
   release:
     runs-on: ubuntu-20.04
@@ -37,9 +59,6 @@ jobs:
       uses: actions/download-artifact@v4
       with:
         merge-multiple: true
-
-    - name: Print
-      run: ls -R
 
     - name: Create Release
       id: create_release
