homework2

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -28,18 +28,37 @@ jobs:
       with:
         path: ${{github.workspace}}/*.deb
         if-no-files-found: error
+  
+  test:
+    runs-on: ubuntu-20.04
+    needs: build
+    steps:
+    - uses: actions/checkout@v2
+    - name: Install tools
+      run: sudo apt install cmake
+
+    - name: Configure CMake
+      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+
+    - name: Build
+      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+    
+    - run: |
+        if [ "24e7a7b2270daee89c64d3ca5fb3da1a  -" = "$(cat ${{github.workspace}}/ip_filter.tsv | /${{github.workspace}}/build/src/ip_filter | md5sum)" ]; then
+        echo "ok"
+        else
+        echo "failed"
+        exit 1
+        fi
 
   release:
     runs-on: ubuntu-20.04
-    needs: build
+    needs: test
     steps:
     - name: Download
       uses: actions/download-artifact@v4
       with:
         merge-multiple: true
-
-    - name: Print
-      run: ls -R
 
     - name: Create Release
       id: create_release
@@ -58,6 +77,6 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ./hello-0.0.${{ github.run_number }}-Linux.deb
-        asset_name: hello-0.0.${{ github.run_number }}-Linux.deb
+        asset_path: ./ip_filter-0.0.${{ github.run_number }}-Linux.deb
+        asset_name: ip_filter-0.0.${{ github.run_number }}-Linux.deb
         asset_content_type: application/vnd.debian.binary-package
